# pandas.read_sql

pandas.read_sqlsqlconindex_col=Nonecoerce_float=Trueparams=Noneparse_dates=Nonecolumns=Nonechunksize=NoneRead SQL query or database table into a DataFrame.

This function is a convenience wrapper around `read_sql_table` and
`read_sql_query` (for backward compatibility). It will delegate
to the specific function depending on the provided input. A SQL query
will be routed to `read_sql_query`, while a database table name will
be routed to `read_sql_table`. Note that the delegated function might
have more specific notes about their functionality not listed here.


<dl style='margin: 20px 0;'>
<dt>Parameters</dt>
<dd>

<dl style='margin: 20px 0;'>
<dt>**sql**</dt>
string or SQLAlchemy Selectable (select or text object)<dd>
SQL query to be executed or a table name.

</dd>
<dt>**con**</dt>
SQLAlchemy connectable (engine/connection) or database string URI<dd>
or DBAPI2 connection (fallback mode)

Using SQLAlchemy makes it possible to use any DB supported by that
library. If a DBAPI2 object, only sqlite3 is supported.

</dd>
<dt>**index_col**</dt>
string or list of strings, optional, default: None<dd>
Column(s) to set as index(MultiIndex).

</dd>
<dt>**coerce_float**</dt>
boolean, default True<dd>
Attempts to convert values of non-string, non-numeric objects (like
decimal.Decimal) to floating point, useful for SQL result sets.

</dd>
<dt>**params**</dt>
list, tuple or dict, optional, default: None<dd>
List of parameters to pass to execute method.  The syntax used
to pass parameters is database driver dependent. Check your
database driver documentation for which of the five syntax styles,
described in PEP 249’s paramstyle, is supported.
Eg. for psycopg2, uses %(name)s so use params={‘name’ : ‘value’}

</dd>
<dt>**parse_dates**</dt>
list or dict, default: None<dd>
- List of column names to parse as dates.  
- Dict of `{column_name: format string}` where format string is
  strftime compatible in case of parsing string times, or is one of
  (D, s, ns, ms, us) in case of parsing integer timestamps.  
- Dict of `{column_name: arg dict}`, where the arg dict corresponds
  to the keyword arguments of `pandas.to_datetime()`
  Especially useful with databases without native Datetime support,
  such as SQLite.  


</dd>
<dt>**columns**</dt>
list, default: None<dd>
List of column names to select from SQL table (only used when reading
a table).

</dd>
<dt>**chunksize**</dt>
int, default None<dd>
If specified, return an iterator where chunksize is the
number of rows to include in each chunk.

</dd>

</dl>

</dd>
<dt>Returns</dt>
<dd>

<dl style='margin: 20px 0;'>
<dt>DataFrame</dt>
<dd>
</dd>

</dl>

</dd>

</dl>


<dl style='margin: 20px 0;'>
<dt>[`read_sql_table`](pandas.read_sql_table#pandas.read_sql_table)</dt>
<dd>
Read SQL database table into a DataFrame.

</dd>
<dt>[`read_sql_query`](pandas.read_sql_query#pandas.read_sql_query)</dt>
<dd>
Read SQL query into a DataFrame.

</dd>

</dl>